import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:oktoast/oktoast.dart';

import '../util/comm.dart';

class DartOutputAreaWidget extends StatefulWidget {
  final TextSpan textSpan;
  final String textContent;
  final String clzName;
  final ScrollController scrollController;
  final TextEditingController dartFileNameController;

  const DartOutputAreaWidget(
      {super.key,
      required this.textSpan,
      required this.scrollController,
      required this.textContent,
      required this.clzName,
      required this.dartFileNameController});

  @override
  State<StatefulWidget> createState() {
    return DartOutputAreaWidgetState();
  }
}

class DartOutputAreaWidgetState extends State<DartOutputAreaWidget> {
  Widget area() {
    return SizedBox(width: double.infinity, child: SelectableText.rich(widget.textSpan));
  }

  @override
  Widget build(BuildContext context) {
    return Container(
        height: double.infinity,
        decoration:
            BoxDecoration(color: Colors.transparent, borderRadius: BorderRadius.circular(4), border: Border.all(color: Colors.green, width: 2)),
        padding: const EdgeInsets.only(left: 10, right: 10, top: 10, bottom: 10),
        child: Stack(children: [
          Padding(
            padding: const EdgeInsets.only(bottom: 40.0),
            child: SingleChildScrollView(controller: widget.scrollController, child: area()),
          ),
          Positioned(
            right: 0,
            bottom: 0,
            child: ElevatedButton(
                onPressed: () {
                  Clipboard.setData(ClipboardData(text: widget.textContent));
                  showToast('拷贝成功');
                },
                child: const Text('拷贝')),
          ),
          Positioned(
            right: 70,
            bottom: 0,
            child: ElevatedButton(
                onPressed: () async {
                  String? path = await FilePicker.platform.getDirectoryPath();

                  if (path == null) {
                    return;
                  }

                  File f = File('$path/${widget.clzName}.dart');
                  f.writeAsString(widget.textContent);

                  showToast('生成桌面文件成功 ${f.path}');
                },
                child: const Text('导出文件到')),
          ),
          Positioned(bottom: 0, right: 260, child: dartClzNameField()),
          Positioned(bottom: 0, right: 190, child: getTipWidget(showTip: '注意', toastTip: '默认的类名为 Autogenerated', showDown: false))
        ]));
  }

  Widget dartClzNameField() {
    return Container(
        constraints: const BoxConstraints(minWidth: 200, maxWidth: 200, maxHeight: 30),
        padding: const EdgeInsets.only(left: 10, right: 10),
        decoration: BoxDecoration(
          border: Border.all(color: Colors.greenAccent, width: 2),
          color: Colors.transparent,
          borderRadius: BorderRadius.circular(5),
        ),
        child: Center(
            child: TextField(
          controller: widget.dartFileNameController,
          readOnly: false,
          minLines: 1,
          cursorColor: Colors.green,
          style: const TextStyle(fontSize: 14),
          maxLines: 1,
          decoration: const InputDecoration(
            border: InputBorder.none,
            hintText: '输入自定义的类名',
            contentPadding: EdgeInsets.only(left: 5, top: 0, right: 5, bottom: 0),
            isCollapsed: true,
          ),
        )));
  }
}
